
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider, SignedIn, SignedOut, SignIn, SignInButton, UserButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IRIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">

      <body
        className="flex h-screen w-screen items-center justify-center" 
      >
        
        <SignedOut>
            <SignIn routing = "hash" />
          </SignedOut>
          <SignedIn>

        {children}
            <UserButton />
          </SignedIn>
          
      </body>
    </html>

    </ClerkProvider>
  );
}
